In [1]:
#Carguemos modulos
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("S:/Universidad/Proyecto/Big Data/it_project/datasets/data_demanda.csv")

In [2]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       90000 non-null  int64  
 1   country                  90000 non-null  object 
 2   job_role                 90000 non-null  object 
 3   ai_specialization        90000 non-null  object 
 4   experience_level         90000 non-null  object 
 5   experience_years         90000 non-null  int64  
 6   salary_usd               90000 non-null  int64  
 7   bonus_usd                90000 non-null  int64  
 8   education_required       90000 non-null  object 
 9   industry                 90000 non-null  object 
 10  company_size             90000 non-null  object 
 11  interview_rounds         90000 non-null  int64  
 12  year                     90000 non-null  int64  
 13  work_mode                90000 non-null  object 
 14  weekly_hours          

In [3]:
data.columns

Index(['id', 'country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary_usd', 'bonus_usd', 'education_required',
       'industry', 'company_size', 'interview_rounds', 'year', 'work_mode',
       'weekly_hours', 'company_rating', 'job_openings',
       'hiring_difficulty_score', 'layoff_risk', 'ai_adoption_score',
       'company_funding_billion', 'economic_index', 'ai_maturity_years',
       'offer_acceptance_rate', 'tax_rate_percent', 'vacation_days',
       'skill_demand_score', 'automation_risk', 'job_security_score',
       'career_growth_score', 'work_life_balance_score', 'promotion_speed',
       'salary_percentile', 'cost_of_living_index', 'employee_satisfaction'],
      dtype='object')

In [14]:
print("--------------------Features-----------------------")

print("-------------------------1. País------------------------------")

print(data['country'].unique())

print("---------------------------2. Roles---------------------------")

print(data['job_role'].unique())

print("-------------------------3. Especialización---------------------------")

print(data['ai_specialization'].unique())

print("--------------------------4. Experiencia--------------------------")

print(data['experience_level'].unique())

print("--------------------------5. Años de Experiencia--------------------------")

print(data['experience_years'].unique())

print("--------------------------6. Salario USD--------------------------")

print(data['salary_usd'].unique())

print("--------------------------7. Bonos USD--------------------------")

print(data['bonus_usd'].unique())

print("--------------------------8. Educación--------------------------")

print(data['education_required'].unique())

print("-------------------------9. Industria---------------------------")

print(data['industry'].unique())

--------------------Features-----------------------
-------------------------1. País------------------------------
['UAE' 'USA' 'Brazil' 'India' 'Germany' 'Japan' 'Australia' 'France'
 'Singapore' 'Netherlands' 'Canada' 'UK']
---------------------------2. Roles---------------------------
['Machine Learning Engineer' 'AI Engineer' 'Research Scientist'
 'Software Engineer AI' 'Data Analyst' 'Computer Vision Engineer'
 'NLP Engineer' 'Data Scientist']
-------------------------3. Especialización---------------------------
['Reinforcement Learning' 'LLM' 'Analytics' 'Computer Vision' 'NLP'
 'MLOps' 'Forecasting' 'Generative AI']
--------------------------4. Experiencia--------------------------
['Entry' 'Senior' 'Mid' 'Lead']
--------------------------5. Años de Experiencia--------------------------
[ 0  1  6  3  9 19 10  5  7  4 12 15 18  8 17 14 16  2 13 11]
--------------------------6. Salario USD--------------------------
[ 66465  75507  41660 ...  91473  91343 166838]
-----------------

In [7]:
print("------------------------10. Tamaño de Empresa----------------------------")

print(data['company_size'].unique())

print("--------------------------11. Rondas de Entrevistas--------------------------")

print(data['interview_rounds'].unique())

print("--------------------------12. Año--------------------------")

print(data['year'].unique())

print("--------------------------13. Modo de Trabajo--------------------------")

print(data['work_mode'].unique())

print("---------------------------14. Horas de Trabajo a la Semana-------------------------")

print(data['weekly_hours'].unique())

print("------------------------15. Rating de la Compañia----------------------------")

print(data['company_rating'].unique())

------------------------10. Tamaño de Empresa----------------------------
['Small' 'Large' 'Medium' 'Startup' 'Enterprise']
--------------------------11. Rondas de Entrevistas--------------------------
[7 3 2 5 4 6]
--------------------------12. Año--------------------------
[2020 2021 2026 2022 2024 2023 2025]
--------------------------13. Modo de Trabajo--------------------------
['Remote' 'Onsite' 'Hybrid']
---------------------------14. Horas de Trabajo a la Semana-------------------------
[44.7 48.9 46.8 52.2 46.7 48.3 36.6 40.2 52.9 40.8 46.5 37.3 38.6 49.9
 47.7 42.5 40.5 51.9 46.9 39.2 47.5 37.1 52.7 50.6 37.7 46.1 51.6 39.8
 49.2 45.2 40.3 53.1 53.3 48.  45.9 42.4 51.3 40.4 45.1 51.5 37.5 47.8
 54.3 41.2 40.  53.9 39.1 52.  45.3 40.1 47.6 46.4 49.6 48.8 43.4 51.
 41.1 51.7 39.5 48.5 49.8 50.5 44.  40.7 48.6 46.6 54.9 39.3 38.1 54.7
 44.3 43.2 43.5 44.8 41.7 40.9 36.1 44.6 47.3 49.7 46.3 39.4 54.1 44.2
 41.6 36.2 43.9 43.8 54.6 43.3 49.3 54.8 43.7 41.9 38.4 42.7 47.4 36.4
 42. 

In [ ]:
print("--------------------------16. Job Openings--------------------------")

print(data['job_openings'].unique())

print("--------------------------17. Hiring Difficulty Score--------------------------")

print(data['hiring_difficulty_score'].unique())

print("--------------------------18. Layoff Risk--------------------------")

print(data['layoff_risk'].unique())

--------------------------16. Job Openings--------------------------
[10 27 23 17 15 14  7  2 22  6 21 35 24 20 18 25 19  1 29 11 28  3 38 13
 26 16 31 32  9 30 34  8 33  4 39 12 37  5 36 40 43 44 41 45 42 46 47 48
 50]
--------------------------17. Hiring Difficulty Score--------------------------
[52.76535076 53.11458013 76.39526308 ... 57.17062553 51.3834059
 38.36024892]
--------------------------18. Layoff Risk--------------------------
[0.404 0.387 0.415 0.115 0.311 0.164 0.042 0.177 0.117 0.104 0.4   0.149
 0.41  0.14  0.11  0.237 0.205 0.074 0.203 0.378 0.068 0.389 0.206 0.
 0.182 0.297 0.175 0.039 0.173 0.22  0.216 0.046 0.012 0.114 0.062 0.263
 0.051 0.127 0.084 0.229 0.151 0.011 0.121 0.165 0.158 0.178 0.162 0.417
 0.125 0.079 0.419 0.063 0.126 0.19  0.098 0.396 0.099 0.106 0.194 0.161
 0.102 0.044 0.105 0.101 0.196 0.331 0.453 0.122 0.171 0.008 0.386 0.132
 0.031 0.224 0.108 0.027 0.021 0.352 0.116 0.095 0.409 0.172 0.36  0.179
 0.035 0.345 0.347 0.384 0.166 0.186 0.358 0.0

In [ ]:
print("---------------------------19. Score de Adopción de IA-------------------------")

print(data['ai_adoption_score'].unique())

print("---------------------------20. Company Funding Billion-------------------------")

print(data['company_funding_billion'].unique())

---------------------------19. Score de Adopción de IA-------------------------
[ 91  71  69  74  68  59  78  73  54  77  76  81  66  75  72  89  50  97
  61  65  70  88  85  83  95  82  39 100  53  86  64  79  93  51  80  32
  67  49  57  87  60  56  62  52  48  84  90  92  44  42  99  94  58  47
  63  98  46  55  96  38  31  45  40  43  28  41  35  36  37  27  30  29
  34  33  25  24  19  22  26  21  15  13   1  12  23   9  16  20]
---------------------------20. Company Funding Billion-------------------------
[3.3  4.39 5.04 4.38 6.67 0.2  3.41 6.81 7.45 5.69 5.52 3.89 1.43 0.64
 8.98 2.62 3.71 4.16 7.09 2.22 2.72 8.24 3.95 0.82 1.32 6.9  5.2  6.88
 6.57 6.09 1.75 4.   0.92 4.41 2.11 2.35 6.01 2.6  7.37 6.33 6.04 2.29
 2.25 7.2  3.38 9.47 0.49 1.7  0.87 8.52 4.12 3.84 7.69 6.4  5.44 7.15
 3.92 4.02 6.25 1.06 4.86 8.55 1.98 3.96 6.21 4.81 1.82 1.39 7.42 1.69
 6.49 6.12 4.46 2.73 4.51 2.21 5.34 1.74 9.31 5.09 8.16 4.36 6.11 2.7
 2.23 2.96 1.28 5.25 0.26 3.11 8.   7.   4.77 8.91 1.55 7

In [11]:
print("------------------------21. Index Economico----------------------------")

print(data['economic_index'].unique())

print("--------------------------22. AI Maturity Years--------------------------")

print(data['ai_maturity_years'].unique())

print("--------------------------23. Offer Acceptance Rate--------------------------")

print(data['offer_acceptance_rate'].unique())

print("--------------------------24. Tax Rate Percent--------------------------")

print(data['tax_rate_percent'].unique())

------------------------21. Index Economico----------------------------
[78.65 62.14 87.47 ... 75.43 72.11 50.04]
--------------------------22. AI Maturity Years--------------------------
[13  8  7  5  4 11  3 14  9  6 10 12]
--------------------------23. Offer Acceptance Rate--------------------------
[60.58 75.8  62.95 ... 80.01 60.36 92.77]
--------------------------24. Tax Rate Percent--------------------------
[20.8 28.4 12.2 35.1 36.1 22.9 31.  41.9 21.8 31.4 32.9 27.7 19.5 30.5
 14.1 24.4 25.5 14.5 41.1 22.6 23.3 20.1 12.1 37.2 15.1 29.4 34.2 39.
 38.3 29.6 28.7 20.2 18.1 16.2 23.9 36.2 24.7 39.3 18.5 21.9 27.6 28.8
 41.7 35.9 12.9 35.  16.4 14.7 41.4 37.9 15.  23.2 19.1 29.9 32.7 21.2
 32.8 27.2 13.9 34.8 35.6 15.2 19.8 12.4 30.4 23.6 39.7 15.8 24.1 38.5
 28.2 39.1 38.8 29.8 18.2 41.8 14.4 15.7 33.2 26.6 40.8 25.3 29.2 15.3
 31.2 26.9 27.  41.2 23.  27.9 33.4 12.3 31.7 23.1 30.7 31.3 20.6 34.5
 31.5 32.6 27.1 12.6 17.2 31.9 19.9 38.7 21.1 32.3 34.4 25.1 33.5 28.6
 26.  39.4 19.

In [ ]:
print("---------------------------25. Dias de Vacaciones-------------------------")

print(data['vacation_days'].unique())

print("--------------------------26. Skill Demand Score--------------------------")

print(data['skill_demand_score'].unique())

print("--------------------------27. Automation Risk--------------------------")

print(data['automation_risk'].unique())

print("--------------------------28. Job Security Score--------------------------")

print(data['job_security_score'].unique())

print("---------------------------29. Career Growth Score-------------------------")

print(data['career_growth_score'].unique())

---------------------------25. Dias de Vacaciones-------------------------
[27 13 30 24 16 18 26 12 17 11 20 14 21 22 19 15 25 29 28 10 23]
--------------------------26. Skill Demand Score--------------------------
[ 12  54  80  82  49  73  34  21  88  65   1  94  70   9  66  13  32  22
  75  11  39  17  27  48  86  53  40  87  69  79  57  26  64  16  58  43
  93  24  61  20 100   2  97  44  98  85  37  71   7   8   3  63  35  59
  50  96  10  78   6  47  60   5  51  29  92  72  74  23  81  33  95   4
  38  90  56  52  19  84  31  15  18  55  41  76  28  67  36  42  89  91
  25  30  14  62  77  99  83  68  45  46]
--------------------------27. Automation Risk--------------------------
[ 76  29  49  47  35  92  96  88  69  98  77  63  97  44  31  85  25   7
  95  24  59  45  34  75  14  86  30  41  40  73  57  19  52  60  22   3
  21  54  36  93  13  38  33  16  79  53  81  11  12  70  37  32   1  42
  87  56  74  68  90  18  89   9  17  46  62   4  78  72  71  83  55  65
  66  48  51 1

In [13]:
print("---------------------------30. Work Life Balance Score-------------------------")

print(data['work_life_balance_score'].unique())

print("------------------------31. Promotion Speed----------------------------")

print(data['promotion_speed'].unique())

print("--------------------------32. Salary Percentile--------------------------")

print(data['salary_percentile'].unique())

print("--------------------------33. Cost Of Living Index--------------------------")

print(data['cost_of_living_index'].unique())

print("--------------------------34. Employee Satisfaction--------------------------")

print(data['employee_satisfaction'].unique())

---------------------------30. Work Life Balance Score-------------------------
[73 51 68 55 69 48 96 77 56 86 70 95 79 78 62 85 49 58 83 89 88 64 98 82
 57 71 94 66 72 67 63 87 65 61 93 80 75 90 54 46 74 43 50 52 81 91 76 84
 59 60 41 53 38 97 40 42 45 92 39 47 32 34 27 36 44 37 33 31 35 26 29 25
 30 28]
------------------------31. Promotion Speed----------------------------
[15 37 46 17 38 67 57 50 31 45 62 55 25 16 39 32 29 54 12 68 34 58 48 24
 27 22 40 30 60 85 69 63 49 21 36 42 47 26 28 64 33 13 71 61 56 83 52 70
 76 80 20 53 18 93 66 74 72 90 59 41 77 43 51 35 19 75 44 65 23 14 82 87
 73 98 96 79 84 81 78 88 92 97 89 95 91 86 94]
--------------------------32. Salary Percentile--------------------------
[ 55  58  13  74  21  82  41  75  97  23  42   9  94   3  36  56  25  84
   1  70  14  71  46  95  29  43  93  86  39  87   4  32  18  54  50  60
  34  96  17  40  90  63 100  73  77  89  48  62  72  76  61  98  57  59
  37  19  69  45  64  65   6  10  68  12  78  52  38  91  20  

In [20]:
print("---------------------------features future demand-------------------------")

print(data['country'].unique())
print(data['job_role'].unique())
print(data['ai_specialization'].unique())
print(data['experience_level'].unique())
print(data['experience_years'].unique())
print(data['education_required'].unique())
print(data['industry'].unique())
print(data['company_size'].unique())
print(data['work_mode'].unique())
print(data['weekly_hours'].unique())

---------------------------features future demand-------------------------
['UAE' 'USA' 'Brazil' 'India' 'Germany' 'Japan' 'Australia' 'France'
 'Singapore' 'Netherlands' 'Canada' 'UK']
['Machine Learning Engineer' 'AI Engineer' 'Research Scientist'
 'Software Engineer AI' 'Data Analyst' 'Computer Vision Engineer'
 'NLP Engineer' 'Data Scientist']
['Reinforcement Learning' 'LLM' 'Analytics' 'Computer Vision' 'NLP'
 'MLOps' 'Forecasting' 'Generative AI']
['Entry' 'Senior' 'Mid' 'Lead']
[ 0  1  6  3  9 19 10  5  7  4 12 15 18  8 17 14 16  2 13 11]
['Master' 'Bootcamp' 'PhD' 'Diploma' 'Bachelor']
['Automotive' 'Retail' 'Healthcare' 'Tech' 'Consulting' 'Telecom' 'Energy'
 'Gaming' 'Education' 'Finance']
['Small' 'Large' 'Medium' 'Startup' 'Enterprise']
['Remote' 'Onsite' 'Hybrid']
[44.7 48.9 46.8 52.2 46.7 48.3 36.6 40.2 52.9 40.8 46.5 37.3 38.6 49.9
 47.7 42.5 40.5 51.9 46.9 39.2 47.5 37.1 52.7 50.6 37.7 46.1 51.6 39.8
 49.2 45.2 40.3 53.1 53.3 48.  45.9 42.4 51.3 40.4 45.1 51.5 37.5 47.8

In [21]:
print(data['weekly_hours'].describe())

print("MIN:", data['weekly_hours'].min())
print("MAX:", data['weekly_hours'].max())

print(data['weekly_hours'].head(20))

count    90000.000000
mean        45.476268
std          5.475497
min         36.000000
25%         40.700000
50%         45.500000
75%         50.200000
max         55.000000
Name: weekly_hours, dtype: float64
MIN: 36.0
MAX: 55.0
0     44.7
1     48.9
2     46.8
3     52.2
4     46.7
5     48.3
6     36.6
7     40.2
8     52.9
9     40.8
10    46.5
11    37.3
12    38.6
13    49.9
14    47.7
15    42.5
16    40.5
17    51.9
18    46.9
19    39.2
Name: weekly_hours, dtype: float64


In [16]:
data.columns

Index(['id', 'country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary_usd', 'bonus_usd', 'education_required',
       'industry', 'company_size', 'interview_rounds', 'year', 'work_mode',
       'weekly_hours', 'company_rating', 'job_openings',
       'hiring_difficulty_score', 'layoff_risk', 'ai_adoption_score',
       'company_funding_billion', 'economic_index', 'ai_maturity_years',
       'offer_acceptance_rate', 'tax_rate_percent', 'vacation_days',
       'skill_demand_score', 'automation_risk', 'job_security_score',
       'career_growth_score', 'work_life_balance_score', 'promotion_speed',
       'salary_percentile', 'cost_of_living_index', 'employee_satisfaction'],
      dtype='object')

In [ ]:
data.columns

Index(['id', 'country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary_usd', 'bonus_usd', 'education_required',
       'industry', 'company_size', 'interview_rounds', 'year', 'work_mode',
       'weekly_hours', 'company_rating', 'job_openings',
       'hiring_difficulty_score', 'layoff_risk', 'ai_adoption_score',
       'company_funding_billion', 'economic_index', 'ai_maturity_years',
       'offer_acceptance_rate', 'tax_rate_percent', 'vacation_days',
       'skill_demand_score', 'automation_risk', 'job_security_score',
       'career_growth_score', 'work_life_balance_score', 'promotion_speed',
       'salary_percentile', 'cost_of_living_index', 'employee_satisfaction'],
      dtype='object')

In [9]:
data.loc[:, ["country", "job_role", "ai_specialization", "experience_level", "education_required", "industry", "company_size", "work_mode", "job_openings", "skill_demand_score", "ai_adoption_score", "automation_risk", "career_growth_score", "job_security_score"]]

,country,job_role,ai_specialization,experience_level,education_required,industry,company_size,work_mode,job_openings,skill_demand_score,ai_adoption_score,automation_risk,career_growth_score,job_security_score
0,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,Master,Automotive,Small,Remote,10,12,91,76,65,57
1,USA,AI Engineer,LLM,Entry,Bootcamp,Retail,Small,Onsite,27,54,71,29,60,69
2,Brazil,Research Scientist,Analytics,Entry,PhD,Healthcare,Large,Remote,10,12,69,49,59,70
3,India,Software Engineer AI,Computer Vision,Senior,Diploma,Tech,Large,Onsite,23,80,74,47,65,79
4,Germany,Machine Learning Engineer,Computer Vision,Entry,Master,Retail,Medium,Hybrid,17,82,68,47,52,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,Germany,Research Scientist,Forecasting,Lead,Bootcamp,Energy,Enterprise,Remote,19,4,75,71,56,85
89996,Germany,Machine Learning Engineer,NLP,Mid,Bootcamp,Gaming,Startup,Hybrid,33,46,66,65,34,71
89997,Singapore,Computer Vision Engineer,Computer Vision,Mid,Bootcamp,Energy,Enterprise,Onsite,16,89,65,6,75,72
89998,Germany,AI Engineer,MLOps,Mid,Bachelor,Education,Medium,Remote,18,83,100,66,66,77


In [26]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import joblib

In [27]:
print(data.head())

   id  country                   job_role       ai_specialization  \
0   1      UAE  Machine Learning Engineer  Reinforcement Learning   
1   2      USA                AI Engineer                     LLM   
2   3   Brazil         Research Scientist               Analytics   
3   4    India       Software Engineer AI         Computer Vision   
4   5  Germany  Machine Learning Engineer         Computer Vision   

  experience_level  experience_years  salary_usd  bonus_usd  \
0            Entry                 0       66465       5395   
1            Entry                 1       75507      11713   
2            Entry                 0       41660       5268   
3           Senior                 6       43268       7975   
4            Entry                 0       69119       4758   

  education_required    industry  ... vacation_days  skill_demand_score  \
0             Master  Automotive  ...            27                  12   
1           Bootcamp      Retail  ...            27     

In [29]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       90000 non-null  int64  
 1   country                  90000 non-null  object 
 2   job_role                 90000 non-null  object 
 3   ai_specialization        90000 non-null  object 
 4   experience_level         90000 non-null  object 
 5   experience_years         90000 non-null  int64  
 6   salary_usd               90000 non-null  int64  
 7   bonus_usd                90000 non-null  int64  
 8   education_required       90000 non-null  object 
 9   industry                 90000 non-null  object 
 10  company_size             90000 non-null  object 
 11  interview_rounds         90000 non-null  int64  
 12  year                     90000 non-null  int64  
 13  work_mode                90000 non-null  object 
 14  weekly_hours          

In [30]:
print(data.isnull().sum())

id                         0
country                    0
job_role                   0
ai_specialization          0
experience_level           0
experience_years           0
salary_usd                 0
bonus_usd                  0
education_required         0
industry                   0
company_size               0
interview_rounds           0
year                       0
work_mode                  0
weekly_hours               0
company_rating             0
job_openings               0
hiring_difficulty_score    0
layoff_risk                0
ai_adoption_score          0
company_funding_billion    0
economic_index             0
ai_maturity_years          0
offer_acceptance_rate      0
tax_rate_percent           0
vacation_days              0
skill_demand_score         0
automation_risk            0
job_security_score         0
career_growth_score        0
work_life_balance_score    0
promotion_speed            0
salary_percentile          0
cost_of_living_index       0
employee_satis

In [31]:
columns = [
    'country',
    'job_role',
    'ai_specialization',
    'experience_level',
    'education_required',
    'industry',
    'company_size',
    'work_mode',
    'skill_demand_score',
    'job_openings',
    'career_growth_score',
    'ai_adoption_score',
    'job_security_score',
    'automation_risk'
]

data = data[columns]

In [32]:
data = data.dropna()

In [33]:
data['demand_score_total'] = (
    data['skill_demand_score'] +
    data['career_growth_score'] +
    data['job_openings']
) / 3

In [34]:
def classify_demand(score):
    if score >= 70:
        return 'Alta'
    elif score >= 40:
        return 'Media'
    else:
        return 'Baja'

In [35]:
data['future_demand'] = data['demand_score_total'].apply(classify_demand)

In [36]:
print(data[['demand_score_total', 'future_demand']].head())

   demand_score_total future_demand
0           29.000000          Baja
1           47.000000         Media
2           27.000000          Baja
3           56.000000         Media
4           50.333333         Media


In [37]:
print(data['future_demand'].value_counts())

future_demand
Media    50227
Baja     39726
Alta        47
Name: count, dtype: int64


In [ ]:
# los datos se dividen en tres partes iguales
print(data['demand_score_total'].describe(percentiles=[0.33, 0.66]))

count    90000.000000
mean        41.727204
std         10.852912
min         10.333333
33%         36.000000
50%         41.666667
66%         47.000000
max         75.666667
Name: demand_score_total, dtype: float64


In [ ]:
def classify_demand(score):
    if score >= 52.8:     # 66%
        return 'Alta'
    elif score >= 35.2:   # 33%
        return 'Media'
    else:
        return 'Baja'

# corregimos la data
data['future_demand'] = data['demand_score_total'].apply(classify_demand)

In [40]:
print(data['future_demand'].value_counts())

future_demand
Media    46715
Baja     27465
Alta     15820
Name: count, dtype: int64


In [ ]:
X = data[
    [
        'country',
        'job_role',
        'ai_specialization',
        'experience_level',
        'education_required',
        'industry',
        'company_size',
        'work_mode',
        'ai_adoption_score',
        'job_security_score',
        'automation_risk',
        'skill_demand_score',
        'job_openings',
        'career_growth_score'
    ]
]

y = data['future_demand']

encoders = {}

for column in X.columns:
    if X[column].dtype == 'object':
        le = LabelEncoder()
        X[column] = le.fit_transform(X[column])

        encoders[column] = le

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

C:\Users\saidh\AppData\Local\Temp\ipykernel_2496\3870287617.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[column] = le.fit_transform(X[column])
C:\Users\saidh\AppData\Local\Temp\ipykernel_2496\3870287617.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[column] = le.fit_transform(X[column])
C:\Users\saidh\AppData\Local\Temp\ipykernel_2496\3870287617.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value in

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [52]:
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

,n_estimators,300
,criterion,'gini'
,max_depth,20
,min_samples_split,5
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [53]:
y_pred = model.predict(X_test)

In [54]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

print("Precision:", precision)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

print("Precision:", precision)

f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)

print("F1 Score:", f1)

Accuracy: 0.9710555555555556
Precision: 0.9710577457412378
Precision: 0.9710577457412378
F1 Score: 0.9710410259573582


In [55]:
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

print(cm)

              precision    recall  f1-score   support

           0       0.97      0.95      0.96      3237
           1       0.97      0.98      0.97      5432
           2       0.97      0.97      0.97      9331

    accuracy                           0.97     18000
   macro avg       0.97      0.97      0.97     18000
weighted avg       0.97      0.97      0.97     18000

[[3091    0  146]
 [   0 5297  135]
 [  91  149 9091]]


In [56]:
joblib.dump(model, 'future_demand_model.pkl')

['future_demand_model.pkl']

In [57]:
joblib.dump(encoders, 'future_demand_encoders.pkl')
joblib.dump(target_encoder, 'future_demand_target_encoder.pkl')

['future_demand_target_encoder.pkl']

In [ ]:
import matplotlib.pyplot as plt

importance = model.feature_importances_

feature_names = X.columns

feature_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importance
})

feature_df = feature_df.sort_values(
    by='Importance',
    ascending=False
)

print(feature_df)

                Feature  Importance
11   skill_demand_score    0.651323
13  career_growth_score    0.141795
12         job_openings    0.075533
8     ai_adoption_score    0.034030
10      automation_risk    0.017508
9    job_security_score    0.015938
0               country    0.011103
5              industry    0.010248
1              job_role    0.009357
2     ai_specialization    0.009282
4    education_required    0.007079
6          company_size    0.006765
3      experience_level    0.005230
7             work_mode    0.004809


In [9]:
#EJEMPLO PARA PREDECIR

import joblib
import pandas as pd

# Cargar modelo
model = joblib.load('S:/Universidad/Proyecto/Big Data/it_project/notebooks/future_demand_model.pkl')

# Cargar encoders
encoders = joblib.load('S:/Universidad/Proyecto/Big Data/it_project/notebooks/future_demand_encoders.pkl')

# Cargar target encoder
target_encoder = joblib.load('S:/Universidad/Proyecto/Big Data/it_project/notebooks/future_demand_target_encoder.pkl')

In [2]:
sample = {
    'country': 'Canada',
    'job_role': 'Software Engineer AI',
    'ai_specialization': 'MLOps',
    'experience_level': 'Mid',
    'education_required': 'Bachelor',
    'industry': 'Tech',
    'company_size': 'Medium',
    'work_mode': 'Hybrid',
    'ai_adoption_score': 65,
    'job_security_score': 60,
    'automation_risk': 40,
    'skill_demand_score': 55,
    'job_openings': 18,
    'career_growth_score': 58
}

In [86]:
if sample['ai_specialization'] is None:
    sample['ai_specialization'] = 'Analytics'

if sample['industry'] is None:
    sample['industry'] = 'Tech'

if sample['company_size'] is None:
    sample['company_size'] = 'Medium'

In [87]:
sample_df = pd.DataFrame([sample])

In [88]:
for column in sample_df.columns:

    if column in encoders:

        sample_df[column] = encoders[column].transform(
            sample_df[column]
        )

In [89]:
prediction = model.predict(sample_df)

In [90]:
predicted_label = target_encoder.inverse_transform(prediction)

print(predicted_label)

['Media']


In [91]:
probabilities = model.predict_proba(sample_df)

print(probabilities)

[[0.04077959 0.03970529 0.91951512]]


In [92]:
response = {
    "prediction": predicted_label[0],

    "confidence": round(
        probabilities.max() * 100,
        2
    ),

    "probabilities": {
        "Baja": round(probabilities[0][0] * 100, 2),
        "Media": round(probabilities[0][1] * 100, 2),
        "Alta": round(probabilities[0][2] * 100, 2)
    },

    "scores": {
        "growth_score": sample['career_growth_score'],
        "security_score": sample['job_security_score'],
        "automation_risk": sample['automation_risk'],
        "ai_adoption_score": sample['ai_adoption_score']
    }
}

print(response)

{'prediction': 'Media', 'confidence': np.float64(91.95), 'probabilities': {'Baja': np.float64(4.08), 'Media': np.float64(3.97), 'Alta': np.float64(91.95)}, 'scores': {'growth_score': 58, 'security_score': 60, 'automation_risk': 40, 'ai_adoption_score': 65}}


In [82]:
print(model.classes_)

[0 1 2]


In [93]:
# 1. Obtienes las probabilidades numéricas de tu muestra
probabilities = model.predict_proba(sample_df)[0]

# 2. Obtienes los números de las clases [0, 1, 2]
classes = model.classes_

# 3. Creas el diccionario traduciendo los números a texto real
probability_dict = {}
for i, class_num in enumerate(classes):
    # Traducimos el número (0, 1 o 2) a su texto original ('Alta', 'Baja', 'Media')
    label_text = target_encoder.inverse_transform([class_num])[0]
    
    # Guardamos en el diccionario con su porcentaje
    probability_dict[label_text] = round(probabilities[i] * 100, 2)

print("Diccionario de probabilidades corregido:")
print(probability_dict)


Diccionario de probabilidades corregido:
{'Alta': np.float64(4.08), 'Baja': np.float64(3.97), 'Media': np.float64(91.95)}


In [10]:
# EJEMPLOS DE PRUEBA
# PERFIL ALTO
"""
sample = {
    'country': 'USA',
    'job_role': 'AI Engineer',
    'ai_specialization': 'LLM',
    'experience_level': 'Senior',
    'education_required': 'Master',
    'industry': 'Finance',
    'company_size': 'Enterprise',
    'work_mode': 'Remote',
    'ai_adoption_score': 90,
    'job_security_score': 85,
    'automation_risk': 25,
    'skill_demand_score': 95,
    'job_openings': 40,
    'career_growth_score': 92
}
"""

# PERFIL MEDIO

"""
sample = {
    'country': 'Canada',
    'job_role': 'Software Engineer AI',
    'ai_specialization': 'MLOps',
    'experience_level': 'Mid',
    'education_required': 'Bachelor',
    'industry': 'Tech',
    'company_size': 'Medium',
    'work_mode': 'Hybrid',
    'ai_adoption_score': 65,
    'job_security_score': 60,
    'automation_risk': 40,
    'skill_demand_score': 55,
    'job_openings': 18,
    'career_growth_score': 58
}
"""

# PERFIL BAJO


sample = {
    'country': 'Brazil',
    'job_role': 'Data Analyst',
    'ai_specialization': 'Analytics',
    'experience_level': 'Entry',
    'education_required': 'Diploma',
    'industry': 'Retail',
    'company_size': 'Small',
    'work_mode': 'Onsite',
    'ai_adoption_score': 20,
    'job_security_score': 35,
    'automation_risk': 90,
    'skill_demand_score': 15,
    'job_openings': 3,
    'career_growth_score': 20
}

# VALORES POR DEFECTO

if sample['ai_specialization'] is None:
    sample['ai_specialization'] = 'Analytics'

if sample['industry'] is None:
    sample['industry'] = 'Tech'

if sample['company_size'] is None:
    sample['company_size'] = 'Medium'

# CONVERTIR A DATAFRAME

sample_df = pd.DataFrame([sample])

# APLICAR ENCODERS

for column in sample_df.columns:

    if column in encoders:

        value = sample_df[column][0]

        # valida si existe
        if value not in encoders[column].classes_:

            print(f"Valor no valido en {column}: {value}")

            # agarra primer valor valido
            sample_df[column] = encoders[column].classes_[0]

        else:

            sample_df[column] = encoders[column].transform(
                sample_df[column]
            )

# PREDICCION

prediction = model.predict(sample_df)

# CONVERTIR PREDICCION A TEXTO

predicted_label = target_encoder.inverse_transform(
    prediction
)[0]

# PROBABILIDADES

probabilities = model.predict_proba(sample_df)[0]

classes = model.classes_

# DICCIONARIO DE PROBABILIDADES

probability_dict = {}

for i, class_num in enumerate(classes):

    # Convertimos número -> texto
    label_text = target_encoder.inverse_transform(
        [class_num]
    )[0]

    probability_dict[label_text] = round(
        probabilities[i] * 100,
        2
    )

# OBTENER NIVEL DE CONFIANZA

confidence = round(
    max(probability_dict.values()),
    2
)

# RESPONSE FINAL

response = {

    "prediction": predicted_label,

    "confidence": confidence,

    "probabilities": probability_dict,

    "scores": {

        "growth_score":
            sample['career_growth_score'],

        "security_score":
            sample['job_security_score'],

        "automation_risk":
            sample['automation_risk'],

        "ai_adoption_score":
            sample['ai_adoption_score']
    }
}

# RESULTADO FINAL

print("\n===== RESULTADO =====\n")
print(response)


===== RESULTADO =====

{'prediction': 'Baja', 'confidence': np.float64(95.82), 'probabilities': {'Alta': np.float64(0.17), 'Baja': np.float64(95.82), 'Media': np.float64(4.01)}, 'scores': {'growth_score': 20, 'security_score': 35, 'automation_risk': 90, 'ai_adoption_score': 20}}
