In [56]:
#Carguemos modulos
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("S:/Universidad/Proyecto/Big Data/it_project/datasets/data_demanda.csv")

In [57]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       90000 non-null  int64  
 1   country                  90000 non-null  object 
 2   job_role                 90000 non-null  object 
 3   ai_specialization        90000 non-null  object 
 4   experience_level         90000 non-null  object 
 5   experience_years         90000 non-null  int64  
 6   salary_usd               90000 non-null  int64  
 7   bonus_usd                90000 non-null  int64  
 8   education_required       90000 non-null  object 
 9   industry                 90000 non-null  object 
 10  company_size             90000 non-null  object 
 11  interview_rounds         90000 non-null  int64  
 12  year                     90000 non-null  int64  
 13  work_mode                90000 non-null  object 
 14  weekly_hours          

In [58]:
data.columns

Index(['id', 'country', 'job_role', 'ai_specialization', 'experience_level',
       'experience_years', 'salary_usd', 'bonus_usd', 'education_required',
       'industry', 'company_size', 'interview_rounds', 'year', 'work_mode',
       'weekly_hours', 'company_rating', 'job_openings',
       'hiring_difficulty_score', 'layoff_risk', 'ai_adoption_score',
       'company_funding_billion', 'economic_index', 'ai_maturity_years',
       'offer_acceptance_rate', 'tax_rate_percent', 'vacation_days',
       'skill_demand_score', 'automation_risk', 'job_security_score',
       'career_growth_score', 'work_life_balance_score', 'promotion_speed',
       'salary_percentile', 'cost_of_living_index', 'employee_satisfaction'],
      dtype='object')

In [59]:
data.loc[:, ["country", "job_role", "ai_specialization", "experience_level", "education_required", "industry", "company_size", "work_mode", "job_openings", "skill_demand_score", "ai_adoption_score", "automation_risk", "career_growth_score", "job_security_score"]]

,country,job_role,ai_specialization,experience_level,education_required,industry,company_size,work_mode,job_openings,skill_demand_score,ai_adoption_score,automation_risk,career_growth_score,job_security_score
0,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,Master,Automotive,Small,Remote,10,12,91,76,65,57
1,USA,AI Engineer,LLM,Entry,Bootcamp,Retail,Small,Onsite,27,54,71,29,60,69
2,Brazil,Research Scientist,Analytics,Entry,PhD,Healthcare,Large,Remote,10,12,69,49,59,70
3,India,Software Engineer AI,Computer Vision,Senior,Diploma,Tech,Large,Onsite,23,80,74,47,65,79
4,Germany,Machine Learning Engineer,Computer Vision,Entry,Master,Retail,Medium,Hybrid,17,82,68,47,52,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,Germany,Research Scientist,Forecasting,Lead,Bootcamp,Energy,Enterprise,Remote,19,4,75,71,56,85
89996,Germany,Machine Learning Engineer,NLP,Mid,Bootcamp,Gaming,Startup,Hybrid,33,46,66,65,34,71
89997,Singapore,Computer Vision Engineer,Computer Vision,Mid,Bootcamp,Energy,Enterprise,Onsite,16,89,65,6,75,72
89998,Germany,AI Engineer,MLOps,Mid,Bachelor,Education,Medium,Remote,18,83,100,66,66,77


In [60]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import joblib

In [61]:
print(data.isnull().sum())

id                         0
country                    0
job_role                   0
ai_specialization          0
experience_level           0
experience_years           0
salary_usd                 0
bonus_usd                  0
education_required         0
industry                   0
company_size               0
interview_rounds           0
year                       0
work_mode                  0
weekly_hours               0
company_rating             0
job_openings               0
hiring_difficulty_score    0
layoff_risk                0
ai_adoption_score          0
company_funding_billion    0
economic_index             0
ai_maturity_years          0
offer_acceptance_rate      0
tax_rate_percent           0
vacation_days              0
skill_demand_score         0
automation_risk            0
job_security_score         0
career_growth_score        0
work_life_balance_score    0
promotion_speed            0
salary_percentile          0
cost_of_living_index       0
employee_satis

In [62]:
data['demand_score_total'] = (
    data['skill_demand_score'] +
    data['career_growth_score'] +
    data['job_openings']
) / 3

In [63]:
print(
    data['demand_score_total']
    .describe(percentiles=[0.33, 0.66])
)

count    90000.000000
mean        41.727204
std         10.852912
min         10.333333
33%         36.000000
50%         41.666667
66%         47.000000
max         75.666667
Name: demand_score_total, dtype: float64


In [64]:
def classify_demand(score):

    if score >= 47:
        return 'Alta'

    elif score >= 36:
        return 'Media'

    else:
        return 'Baja'

In [65]:
data['future_demand'] = (
    data['demand_score_total']
    .apply(classify_demand)
)

In [66]:
print(
    data['future_demand']
    .value_counts()
)

future_demand
Alta     31330
Media    29489
Baja     29181
Name: count, dtype: int64


In [67]:
features = [
    'skill_demand_score',
    'career_growth_score',
    'job_openings',
    'job_security_score',
    'automation_risk',
    'ai_adoption_score'
]

In [68]:
X = data[features]

y = data['future_demand']

In [69]:
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

In [70]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [71]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    class_weight='balanced'
)

model.fit(
    X_train,
    y_train
)

,n_estimators,300
,criterion,'gini'
,max_depth,20
,min_samples_split,5
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [72]:
y_pred = model.predict(X_test)

In [73]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)

f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.9820555555555556
Precision: 0.982055881180103
Recall   : 0.9820555555555556
F1 Score : 0.9820508720711265


In [74]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[6172    0   94]
 [   0 5775   61]
 [  70   98 5730]]


In [75]:
import joblib

joblib.dump(
    model,
    'future_demand_model.pkl'
)

['future_demand_model.pkl']

In [76]:
joblib.dump(
    target_encoder,
    'future_demand_encoder.pkl'
)

['future_demand_encoder.pkl']